
site_name: FedeasLab
site_dir: ../FEDEASdocs

nav:
- About: 'about.md'

- Getting Started:
  - Quick Start: 'quick.md'
  - Data Structures: 'DataStructs.md'
  - Schemas: 'dat/README.md'
  - Schemas-2: 'sch/index'

- Functions:
  - Index: 'FEDEASLab/index.md'
  - Libraries:
    - Materials: 'matlib.md'
    - Elements: 'elemlib.md'
    - Modeling Library: 'ModelLib.md'
    - Section Library: 'FEDEASLab/src/Section_Library/'
    - Solution Library: 'FEDEASLab/src/Solution_Library/'
  - Basic analysis: 'FEDEASLab/Basic/FEDEASLab.md'
  - Transient analysis: 'FEDEASLab/Dynamics/'
  - Plastic Analysis: 'FEDEASLab/Plastic_Analysis/LimEqns_2dFrm.md'
  - Core: 'FEDEASLab/General/FEDEASLab.md'
  
- Examples: examples/index.md

theme:
  name: lumen
  # highlightjs: true # Code snippet syntax highlighting
  custom_dir: docs/theme 
  # custom_dir: custom_theme


extra_css:
    - css/extra.css

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - tables
    - mdx_math:
        enable_dollar_delimiter: true 
    - meta
  
google_analytics: 
  - UA-170527070-1
  - auto
