
site_name: FedeasLab
site_dir: ../../FEDEASdocs

nav:
- Home: 'index.md'

- Getting Started:
  - Quick Start: 'quick.md'
  - Data Structures: 'DataStructs.md'

- Functions:
  - Index: 'FEDEASLab.md'
  - Libraries:
    - Materials: 'matlib.md'
    - Elements: 'elemlib.md'
  - Basic analysis: 'FEDEASLab/Basic/FEDEASLab.md'
  - Transient analysis: 'FEDEASLab/Dynamics/FEDEASLab.md'
  - Plastic Analysis: 'FEDEASLab/Plastic_Analysis/LimEqns_2dFrm.md'
  - Core: 'FEDEASLab/General/FEDEASLab.md'
  - Section Library: 'FEDEASLab/Section_Library/FEDEASLab.md'
  - Solution Library: 'FEDEASLab/Solution_Library/FEDEASLab.md'
  - Utilities: 'FEDEASLab/Utilities/FEDEASLab.md'

- Examples: examples/index.md

theme:
  name: lumen
  highlightjs: true # Code snippet syntax highlighting
  custom_dir: docs/theme 

# theme_dir: custom_theme

extra_css:
    - css/extra.css

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - tables
    - mdx_math
    - meta
    # - mdx_snippets
