Description of Create_PanelZone
Home > src > Other > Create_PanelZone.m
Create_PanelZone
PURPOSE
% Clear memory and close any open windows
SYNOPSIS
This is a script file.
DESCRIPTION
% Clear memory and close any open windows
CROSS-REFERENCE INFORMATION
This function calls:
CleanStart CLEANSTART initializes workspace for new analysis
Create_MRFrame CREATE_FRAME generation of nodes and elements for regular N-story, M-bay MR frame
Units % Script file for common unit definition with Imperial units as default
This function is called by:
SOURCE CODE
%% Clear memory and close any open windows
CleanStart
% insert file of units
Units
% save name of script in variable ModelName
ModelName = mfilename;
%% no of stories nst
nst = 4;
%% no of bays nby
nby = 3;
%% typical story height
Hs  = 13*ft;
% specify individual story heights in row vector
Hsv = [Hs+2*ft repmat(Hs,1,nst-1)];
%% typical bay length
Lb = 20*ft;
% specify individual bay lengths in row vector
Lbv = repmat(Lb,1,nby);
% number of girder subelements
nsub = 1;
%% call function to generate node coordinates, element connectivity
Frame = Create_MRFrame (Lbv,Hsv,nsub);
ElemSize_4S3BFrame
nn  = Frame.nn;
ne  = Frame.ne;
XYZ = Frame.XYZ;
CON = Frame.CON;
JntOff = Create_JntOffsets (Frame,'AISC_Section');
% [XYZ,CON] = Add_PanelZone(XYZ,CON,JntOff);
%% the following commands have been incorporated in the function Add_PanelZone
% ------------------------------------------------------------------------------------------
% create data structure for panel connectivity
Panel(1:nn) = struct('CON',[]);
nc = nn;
% loop over elements and add additional nodes for panel zone
for el = 1:ne
  ni  = CON(el,1);
  nj  = CON(el,2);
  xyz = XYZ([ni nj],:);
  xyzAdd = xyz + JntOff{el}';
  xyzTmp = [xyz;xyzAdd];
  [~,iA] = unique(xyzTmp,'rows');
  IAdd = any(iA==3);
  JAdd = any(iA==4);
  if IAdd
    nc = nc+1;
    CON(el,1) = nc;
    Panel(ni).CON = [ Panel(ni).CON  nc ];
    XYZ(nc,:) = xyzTmp(3,:);
  end
  if JAdd
    nc = nc+1;
    CON(el,2) = nc;
    Panel(nj).CON = [ Panel(nj).CON  nc ];
    XYZ(nc,:) = xyzTmp(4,:);
  end
end
% remove nodes without elements connecting to them
% RetInd = index of nodes to retain
RetInd = arrayfun (@(nd) isempty(Panel(nd).CON),1:nn,'UniformOutput',false);
RetInd = [RetInd{:}];
NodOr  = 1:nn;
% node numbers to retain
RetNd  = NodOr(RetInd);
nnTot  = size(XYZ,1);
NodInd = [RetNd nn+1:nnTot];
% update coordinate array with
XYZ    = XYZ(NodInd,:);
NdRem = nn-length(RetNd);
NdIx  = CON>NdRem;
CON(NdIx) = CON(NdIx)-NdRem;
RemInd = ~RetInd;
Panel  = Panel(RemInd);
nPan   = length(Panel);
for np = 1:nPan
  NdId = Panel(np).CON-NdRem;
  xyzp = XYZ(NdId,:);
  [~,N1] = max(xyzp(:,1));
  [~,N2] = max(xyzp(:,2));
  [~,N3] = min(xyzp(:,1));
  [~,N4] = min(xyzp(:,2));
  CONTmp = NdId ([ N1 N2 N3 N4 ]);
  if N3==N4, CONTmp(3) = 0; end
  if N1==N4, CONTmp(1) = 0; end
  if N1==N2 || N2==N3, CONTmp(2) = 0; end
  Panel(np).CON = CONTmp;
end
% if ~iscell(CON), CON = num2cell(CON,2); end
% [CON{ne+1:ne+nPan}] = Panel(:).CON;
%-------------------------------------------------------------------------------------------
%% boundary conditions for fixed base of frame
% find nodes at base
Bnodes = find(XYZ(:,2)==0);
BOUN(Bnodes,:) = repmat([1 1 1],length(Bnodes),1);
%% specify element type (can change later)
ne = length(CON);
[ElemName{1:ne}] = deal ('LE2dFrm');       % 2d linear frame element
%% generate Model data structure
Model = Create_SimpleModel (XYZ,CON,BOUN,ElemName);
% plot parameters
% -------------------------------------------------------------------------
WinXr = 0.40;    % X-ratio of plot window to screen size
WinYr = 0.80;    % Y-ratio of plot window to screen size
% -------------------------------------------------------------------------
Create_Window(WinXr,WinYr);
PlotOpt.PlNod = 'yes';
PlotOpt.PlBnd = 'yes';
PlotOpt.LnWth = 1;
PlotOpt.NodSF = 0.3;
Plot_Model (Model,[],PlotOpt);    % plot model
% PlotOpt.FntSF = 0.4;
% Label_Model (Model,PlotOpt);       % label model
clear PlotOpt
% el = 1:Frame.ne;
% if ~iscell(Frame.CON), CON = num2cell(Frame.CON,2); end
% ID = arrayfun (@(el) Frame.XYZ(CON{el},:),el,'UniformOutput',false);
%
% XYZAdd = ([ID{:}]+[JntOff{:}])';